from CropRecommendationApp.models import crop

crops = [
    ('rice',        'Rice is a staple cereal crop that forms the primary diet for over half the world. It thrives in hot, humid climates with abundant rainfall and deep, water-retentive clayey soils. High nitrogen levels and controlled irrigation are essential for maximizing the yield of this semi-aquatic plant.', 'Cereal', 'upload_images/crop/rice.jpg'),
    ('maize',       'Maize is a highly versatile and globally important cereal crop used for human consumption, livestock feed, and industrial products. It grows vigorously in warm climates with moderate rainfall. Rich, well-drained loamy soil with plenty of sunshine and nitrogen is key to producing a heavy, healthy yield.', 'Cereal', 'upload_images/crop/maize.jpg'),
    ('chickpea',    'Chickpea is a protein-rich legume that plays a vital role in vegetarian diets worldwide. It grows exceptionally well in dry, cool conditions and requires minimal rainfall. Because of its deep taproot system, it can withstand drought and prefers well-drained sandy loam soils over waterlogged fields.', 'Legume', 'upload_images/crop/chickpea.jpg'),
    ('kidneybeans', 'Kidney beans are incredibly nutrient-dense legumes packed with fiber and protein. They require moderate temperatures and a frost-free growing period to thrive. Well-drained soils with good organic matter and steady, balanced watering schedules lead to optimal pod formation and robust health.', 'Legume', 'upload_images/crop/kidneybeans.jpg'),
    ('pigeonpeas',  'Pigeon peas are remarkably drought-tolerant legumes widely cultivated in warm, semi-arid conditions. They are deeply rooted, allowing them to draw moisture from subsoil layers. Cultivating pigeon peas also naturally enriches the soil with nitrogen, making them excellent for crop rotation.', 'Legume', 'upload_images/crop/pigeonpeas.jpg'),
    ('mothbeans',   'Moth beans are incredibly resilient legumes that are famously drought-resistant and perfectly suited for arid and semi-arid regions. They thrive in sandy soils with minimal moisture. This fast-growing crop is primarily cultivated for its highly nutritious seeds and functions well as a protective cover crop.', 'Legume', 'upload_images/crop/mothbeans.jpg'),
    ('mungbean',    'Mung beans are fast-growing, warm-season legumes that flourish in humid tropical climates. They demand well-drained loamy soils and are highly valued for their quick maturity, usually ready to harvest in 60-90 days. They are a rich source of plant-based protein and actively improve soil fertility.', 'Legume', 'upload_images/crop/mungbean.jpg'),
    ('blackgram',   'Black gram is a highly nutritious legume predominantly grown in tropical regions with moderate rainfall. It thrives in heavy, moisture-retentive soils and warm weather. Highly prized in South Asian cuisine, it is a sturdy crop that also acts as an excellent natural nitrogen fixer for agricultural fields.', 'Legume', 'upload_images/crop/blackgram.jpg'),
    ('lentil',      'Lentils are cool-season legumes known for their lens-shaped seeds and high protein content. They are highly adaptable to dry, low-rainfall conditions and thrive in well-drained, moderately fertile soils. Lentils are a staple in diverse diets and are celebrated for their minimal water requirements.', 'Legume', 'upload_images/crop/lentil.jpg'),
    ('pomegranate', 'Pomegranate is a premium fruit crop that thrives in hot, dry climates. It boasts a remarkably high tolerance for low humidity and arid conditions. Requiring well-drained soils and intense sunshine, pomegranates produce antioxidant-rich fruits and can tolerate slightly alkaline and saline environments.', 'Fruit', 'upload_images/crop/pomegranate.jpg'),
    ('banana',      'Banana is a fast-growing tropical fruit crop that demands a consistently warm climate and high humidity. It requires exceptionally nutrient-rich, deep soils with high nitrogen and potassium levels. Constant moisture and protection from strong winds are essential for developing heavy, healthy fruit bunches.', 'Fruit', 'upload_images/crop/banana.jpg'),
    ('mango',       'Mango is widely revered as the king of fruits, thriving optimally in hot, dry climates with a distinct dry season to stimulate flowering. It requires deep, well-drained soils and lots of sunshine. Once established, mango trees are deeply rooted and can withstand considerable drought conditions.', 'Fruit', 'upload_images/crop/mango.jpg'),
    ('grapes',      'Grapes are a highly lucrative fruit crop requiring specific temperate to subtropical climates with hot, dry summers and cool winters. They are heavily dependent on high potassium levels for optimal sugar development. Well-drained, rocky or sandy soils usually yield the best quality grapes for consumption.', 'Fruit', 'upload_images/crop/grapes.jpg'),
    ('watermelon',  'Watermelon is a classic warm-season, trailing vine fruit that needs long periods of hot weather to mature. It requires deep, well-drained sandy loam soil with high nitrogen content during early growth. Consistent irrigation is vital during fruit development to ensure a sweet, juicy, and large harvest.', 'Fruit', 'upload_images/crop/watermelon.jpg'),
    ('muskmelon',   'Muskmelon is an aromatic, sweet fruit that demands high humidity, plenty of sunshine, and relatively low rainfall to prevent fungal diseases. It thrives best in warm, sandy loam soils that drain quickly. Proper potassium nutrition is necessary to enhance the fruit’s signature sweetness and firm texture.', 'Fruit', 'upload_images/crop/muskmelon.jpg'),
    ('apple',       'Apple is a premier temperate fruit crop requiring significant winter chilling hours to break dormancy. It thrives in cool temperatures and needs soils rich in phosphorus and potassium. Well-aerated, deep loamy soils with excellent drainage are crucial to prevent root diseases and ensure a crisp harvest.', 'Fruit', 'upload_images/crop/apple.jpg'),
    ('orange',      'Orange is a highly popular citrus fruit suited for subtropical climates with high humidity and abundant sunshine. It requires deep, well-drained soils and is sensitive to waterlogging. Regular irrigation and a balanced supply of micronutrients ensure the production of sweet, juicy, and high-quality fruit.', 'Fruit', 'upload_images/crop/orange.jpg'),
    ('papaya',      'Papaya is an incredibly fast-growing tropical fruit tree that demands a continuously warm climate and high humidity. It is highly sensitive to frost and waterlogging, requiring extremely well-drained soils. Regular fertilization and consistent moisture are key to sustaining its continuous fruit production.', 'Fruit', 'upload_images/crop/papaya.jpg'),
    ('coconut',     'Coconut palms are iconic tropical trees that thrive in highly humid, coastal regions with abundant and well-distributed rainfall. They require deep, sandy or loamy soils with good drainage. Coconuts are highly tolerant of salinity and provide incredibly versatile products ranging from water to copra.', 'Fruit', 'upload_images/crop/coconut.jpg'),
    ('cotton',      'Cotton is a globally vital cash crop prized for its natural fiber. It requires long, frost-free warm temperatures and plenty of sunshine. Deep, moisture-retentive black soils are ideal. While it needs good soil moisture during growth, dry and sunny weather is absolutely critical during the boll ripening phase.', 'Cash', 'upload_images/crop/cotton.jpg'),
    ('jute',        'Jute is a highly profitable natural fiber cash crop famously known as the golden fiber. It thrives exclusively in warm, highly humid conditions with heavy, monsoon-like rainfall. Deep alluvial soils and standing water are optimal for its rapid vegetative growth and the subsequent fiber extraction process.', 'Cash', 'upload_images/crop/jute.jpg'),
    ('coffee',      'Coffee is a premium beverage cash crop that grows best in shaded, subtropical highlands with ample, well-distributed rainfall. It demands deep, fertile, and slightly acidic volcanic soils with excellent drainage. A distinct dry season is necessary to trigger the uniform flowering of its fragrant white blossoms.', 'Cash', 'upload_images/crop/coffee.jpg'),
    ('sugarcane',   'Sugarcane is a massive, perennial cash crop cultivated extensively for sugar production. It requires a long, warm growing season with high temperatures and abundant rainfall. Deep, nutrient-rich soils with heavy fertilization, particularly nitrogen, are required to sustain its intense vegetative growth.', 'Cash', 'upload_images/crop/sugarcane.jpg'),
    ('tea',         'Tea is an evergreen shrub cultivated for its leaves to produce the world’s most popular beverage. It thrives on elevated hill slopes with well-distributed, heavy rainfall and high humidity. The soil must be highly acidic, deep, and perfectly drained, as tea roots are extremely sensitive to water stagnation.', 'Cash', 'upload_images/crop/tea.jpg'),
    ('groundnut',   'Groundnut, or peanut, is a major oilseed and protein crop grown primarily during the warm Kharif season. It uniquely develops its pods underground, requiring light, sandy, well-drained soils to allow the pegs to penetrate easily. It is fairly drought-tolerant but needs moisture during the flowering stage.', 'Oilseed', 'upload_images/crop/groundnut.jpg'),
    ('soybean',     'Soybean is an incredibly protein-rich and versatile oilseed crop grown widely across central regions. It flourishes in warm, moist climates with well-drained, fertile loamy soils. It acts as an excellent soil conditioner by fixing atmospheric nitrogen and is pivotal for both human and animal nutrition.', 'Oilseed', 'upload_images/crop/soybean.jpg'),
    ('turmeric',    'Turmeric is a high-value commercial spice crop known for its vibrant color and medicinal properties. It demands a consistently warm and highly humid climate with substantial rainfall. Loose, well-drained loamy or alluvial soils are absolutely essential for the proper development of its underground rhizomes.', 'Spice', 'upload_images/crop/turmeric.jpg'),
    ('wheat',       'Wheat is a foundational winter (rabi) cereal crop that forms the dietary backbone for millions. It requires a cool, moist growing season followed by bright, dry sunshine for ripening. Heavy loamy or clayey soils that retain moisture well are ideal for producing high-quality, protein-rich grain yields.', 'Cereal', 'upload_images/crop/wheat.jpg'),
    ('bajra',       'Pearl millet, commonly known as Bajra, is an exceptionally hardy and drought-tolerant cereal crop. It thrives in hot, dry environments where other crops fail, making it a staple in arid regions. It grows excellently in light, sandy soils and requires very little rainfall or chemical fertilization to succeed.', 'Cereal', 'upload_images/crop/bajra.jpg'),
    ('ragi',        'Finger millet, or Ragi, is a deeply nutritious cereal crop renowned for its exceptionally high calcium and iron content. It is a highly resilient crop grown in dry, rainfed regions. It adapts well to shallow, lateritic soils and provides a reliable harvest even under erratic weather and poor soil conditions.', 'Cereal', 'upload_images/crop/ragi.jpg'),
    ('mustard',     'Mustard is a prominent winter (rabi) oilseed crop known for its bright yellow blooms. It prefers a cool, dry climate and clear skies. It is highly adaptable but yields best in well-drained, sandy loam soils. It requires less water than wheat, making it highly suitable for areas with limited winter rainfall.', 'Oilseed', 'upload_images/crop/mustard.jpg'),
    ('jowar',       'Sorghum, known locally as Jowar, is a robust, heat-tolerant cereal crop predominantly grown under rainfed conditions. It features an extensive root system that enables it to endure severe drought. It thrives in heavy black or loamy soils and serves as a crucial dual-purpose crop providing both food and fodder.', 'Cereal', 'upload_images/crop/jowar.jpg'),
]

for name, details, category, image in crops:
    obj, created = crop.objects.update_or_create(
        crop_name=name,
        defaults={
            'crop_details': details,
            'crop_category': category,
            'crop_image': image,
        }
    )
    print(f"{'Created' if created else 'Updated'}: {name}")

print("Done.")