# Generated by Django 5.2.7 on 2026-05-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropRecommendationApp', '0006_delete_fertilizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Fertilizer Name')),
                ('description', models.TextField(max_length=500, verbose_name='Fertilizer Details')),
            ],
        ),
        migrations.CreateModel(
            name='fertilizer_recommed',
            fields=[
                ('fr_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Fertilizer Recommend ID')),
                ('fr_farmername', models.CharField(max_length=100, verbose_name='Farmer Name')),
                ('fr_crop', models.CharField(max_length=100, verbose_name='Crop Type')),
                ('fr_soil', models.CharField(max_length=100, verbose_name='Soil Type')),
                ('fr_nitrogen', models.PositiveIntegerField(verbose_name='Soil Nitrogen')),
                ('fr_phosphorous', models.PositiveIntegerField(verbose_name='Soil Phosphorous')),
                ('fr_potassium', models.PositiveIntegerField(verbose_name='Soil Potassium')),
                ('fr_temperature', models.FloatField(verbose_name='Soil Temperature')),
                ('fr_humidity', models.FloatField(verbose_name='Relative Humidity')),
                ('fr_moisture', models.FloatField(verbose_name='Soil Moisture')),
                ('fr_fertilizer', models.CharField(max_length=100, verbose_name='Recommended Fertilizer')),
            ],
        ),
        migrations.AlterField(
            model_name='crop_recommed',
            name='cr_humidity',
            field=models.FloatField(verbose_name='Relative Humidity'),
        ),
        migrations.AlterField(
            model_name='crop_recommed',
            name='cr_ph',
            field=models.FloatField(verbose_name='Soil pH'),
        ),
        migrations.AlterField(
            model_name='crop_recommed',
            name='cr_rainfall',
            field=models.FloatField(verbose_name='Rainfall'),
        ),
        migrations.AlterField(
            model_name='crop_recommed',
            name='cr_temperature',
            field=models.FloatField(verbose_name='Soil Temperature'),
        ),
    ]
